NHL Best vs Rest 

NHL sponsorship revenue totaled northward of $1.28 billion by the end of the 2023 postseason according to SportsPro media. This is a 21% year over year gain when put into context and can be considered a material increase. More oportunities for sponsorship rise especially considering the number of fans that prospects bring with them to the NHL. Organizations looking to advertise through NHL franchises would need rookie information to predict from which amatuer team the first overall pick will come from and to which team he will be drafted by.

https://www.sportspromedia.com/news/nhl-sponsorship-revenue-2022-23-sponsorunited-marketing-report/?zephr_sso_ott=3n4fcM#:~:text=The%20National%20Hockey%20League%20(NHL,North%20American%20ice%20hockey%20property.

https://thehockeynews.com/nhl/chicago-blackhawks/features/corporate-connor-from-cards-to-cars-bedard-already-has-list-of-sponsorships

In [7]:
%pip install lxml
import pandas as pd
import numpy as np 
from bs4 import BeautifulSoup 
import csv 
import requests 



rdfcols = ['year', 'player', 'team', 'amateur team (league)']
rookiesdata = pd.DataFrame(columns=rdfcols)

Requirement already satisfied: lxml in /usr/local/python/3.10.8/lib/python3.10/site-packages (4.9.3)
Note: you may need to restart the kernel to use updated packages.

Creating a dataset, df, in which to land the data from hockey reference website and building the web scraper.



Utilizing BeautifulSoup4 (BS4)


The website from which data is being acquired from (https://www.hockey-reference.com/draft/) is static, therefore, BeautifulSoup4 will be useful in acquiring respective data. However, the content from a website's html doc is needed for BeautifulSoup to scrape data from the website. 
"requests" is a package that requests for the html text behind the website. The html text can be passed into the BS4 scraper once the request is granted and urllib receives the data.

Utilizing Pandas 

For this specific project, however, utilizing BS4 is not so necessary because Pandas offers a built in read_html() function. 
Pandas' read_html function looks specifically for for tables in an html doc. The table on the website is returned as a list object.
The website of interest displays tables on its interface of NHL first round picks data. 
Hockey references posts tables of data, therefore, utilizing Pandas' pre-existing function for obtaining data from html is preferred.

#here we import BeautifulScrape2

In [32]:
import requests
import pandas as pd 
#import regex as re

#create url request
#note that self is a response object when you hover mouse over it
websiteurl = 'https://www.hockey-reference.com/draft/'
#self.response = requests.get(websiteurl)

#pass the html in bs4 scraper
#note that self is an 
#soup = BeautifulSoup(self.response.content, "html.parser")

#find data 
#tablecols = soup.find('tr').text
#year = soup.find('td', class_="left").text
#rows = soup.find('table').text
rookiesdata1 = pd.read_html('https://www.hockey-reference.com/draft/')[0]
#re.findall([0-9]{4}, rookiesdata1.Draft[0])
rookiesdata.year = rookiesdata1.Draft
#show data
#print(rookiesdata.year)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2328882278.py, line 19)

In [16]:
rookiesdata1

,Draft,Team,First Pick,Amateur Team
0,2023 NHL Entry,Chicago Blackhawks,Connor Bedard,Regina Pats (WHL)
1,2022 NHL Entry,Montreal Canadiens,Juraj Slafkovsky,TPS (Finland)
2,2021 NHL Entry,Buffalo Sabres,Owen Power,Michigan (Big Ten)
3,2020 NHL Entry,New York Rangers,Alexis Lafreniere,Rimouski Oceanic (QMJHL)
4,2019 NHL Entry,New Jersey Devils,Jack Hughes,USA U-18 Development Team (USDP/USHL)
...,...,...,...,...
56,1967 NHL Amateur,Los Angeles Kings,Rick Pagnutti,Garson (NOJHL)
57,1966 NHL Amateur,Boston Bruins,Barry Gibbs,Estevan (SJHL)
58,1965 NHL Amateur,New York Rangers,Andre Veilleux,Montreal Rangers Jr. B ()
59,1964 NHL Amateur,Detroit Red Wings,Claude Gauthier,Rosemount (QMJHL)
60,1963 NHL Amateur,Montreal Canadiens,Garry Monahan,St. Michael's Majors ()

Collecting lxml
  Downloading lxml-4.9.3-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading lxml-4.9.3-cp310-cp310-manylinux_2_28_x86_64.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 51.1 MB/s eta 0:00:00:00:010:01
Installing collected packages: lxml
Successfully installed lxml-4.9.3

[               Draft                Team         First Pick  \
 0     2023 NHL Entry  Chicago Blackhawks      Connor Bedard
 1     2022 NHL Entry  Montreal Canadiens   Juraj Slafkovsky
 2     2021 NHL Entry      Buffalo Sabres         Owen Power
 3     2020 NHL Entry    New York Rangers  Alexis Lafreniere
 4     2019 NHL Entry   New Jersey Devils        Jack Hughes
 ..               ...                 ...                ...
 56  1967 NHL Amateur   Los Angeles Kings      Rick Pagnutti
 57  1966 NHL Amateur       Boston Bruins        Barry Gibbs
 58  1965 NHL Amateur    New York Rangers     Andre Veilleux
 59  1964 NHL Amateur   Detroit Red Wings    Claude Gauthier
 60  1963 NHL Amateur  Montreal Canadiens      Garry Monahan

                              Amateur Team
 0                       Regina Pats (WHL)
 1                           TPS (Finland)
 2                      Michigan (Big Ten)
 3                Rimouski Oceanic (QMJHL)
 4   USA U-18 Development Team (USDP/USHL)
 ..                                    ...
 56                         Garson (NOJHL)
 57                         Estevan (SJHL)
 58              Montreal Rangers Jr. B ()
 59                      Rosemount (QMJHL)
 60                St. Michael's Majors ()

 [61 rows x 4 columns],
                 Franchise  From    To
 0           Anaheim Ducks  1993  2023
 1         Arizona Coyotes  1979  2023
 2           Boston Bruins  1963  2023
 3          Buffalo Sabres  1970  2023
 4          Calgary Flames  1972  2023
 5     Carolina Hurricanes  1979  2023
 6      Chicago Blackhawks  1963  2023
 7        Cleveland Barons  1967  1977
 8      Colorado Avalanche  1979  2023
 9   Columbus Blue Jackets  2000  2023
 10           Dallas Stars  1967  2023
 11      Detroit Red Wings  1963  2023
 12        Edmonton Oilers  1979  2023
 13       Florida Panthers  1993  2023
 14      Los Angeles Kings  1967  2023
 15         Minnesota Wild  2000  2023
 16     Montreal Canadiens  1963  2023
 17    Nashville Predators  1998  2023
 18      New Jersey Devils  1974  2023
 19     New York Islanders  1972  2023
 20       New York Rangers  1963  2023
 21        Ottawa Senators  1992  2023
 22    Philadelphia Flyers  1967  2023
 23    Pittsburgh Penguins  1967  2023
 24        San Jose Sharks  1991  2023
 25         Seattle Kraken  2021  2023
 26        St. Louis Blues  1968  2023
 27    Tampa Bay Lightning  1992  2023
 28    Toronto Maple Leafs  1963  2023
 29      Vancouver Canucks  1970  2023
 30   Vegas Golden Knights  2017  2023
 31    Washington Capitals  1974  2023
 32          Winnipeg Jets  1999  2023]

In [2]:

#connecting to city of new york traffic violations data 
%pip install sodapy

from sodapy import Socrata

# Unauthenticated client only works with public data sets. 
# Note 'None'in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us", None)

# Example authenticated client (needed for non-public datasets):
#client = Socrata(data.cityofnewyork.us,
#                  H06gNuS9z8PJ4ivj6XA7B5U2p,
#                  username="bbesthof@mail.yu.edu",
#                  password="Zabzab@1992")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("jt7v-77mi", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

Collecting sodapy
  Downloading sodapy-2.2.0-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: requests>=2.28.1 in /home/codespace/.local/lib/python3.10/site-packages (from sodapy) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.28.1->sodapy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.28.1->sodapy) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.28.1->sodapy) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.28.1->sodapy) (2023.7.22)
Installing collected packages: sodapy
Successfully installed sodapy-2.2.0

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

Note: you may need to restart the kernel to use updated packages.

In [18]:
results_df

,summons_number,plate_id,registration_state,plate_type,issue_date,violation_code,vehicle_body_type,vehicle_make,issuing_agency,street_code1,...,to_hours_in_effect,vehicle_color,unregistered_vehicle,vehicle_year,meter_number,feet_from_curb,intersecting_street,time_first_observed,violation_legal_code,violation_post_code
0,1361929741,FCJ5493,NY,PAS,1970-12-18T00:00:00.000,20,SUBN,GMC,S,35030,...,ALL,BLACK,0,2013,-,0,NaN,NaN,NaN,NaN
1,1366962000,63540MC,NY,COM,1971-02-02T00:00:00.000,46,DELV,FRUEH,P,58830,...,ALL,BRN,0,2013,-,0,NaN,NaN,NaN,NaN
2,1342296187,GCY4187,NY,SRF,1971-09-18T00:00:00.000,21,VAN,FORD,S,11790,...,1100A,BLUE,0,2002,-,0,NaN,NaN,NaN,NaN
3,1342296199,95V6675,TX,PAS,1971-09-18T00:00:00.000,21,NaN,GMC,S,11790,...,1100A,SILVR,0,2008,-,0,NaN,NaN,NaN,NaN
4,1342296217,FYM5117,NY,SRF,1971-09-18T00:00:00.000,21,SUBN,NISSA,S,28190,...,1100A,WHITE,0,2012,-,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1358688722,T637012C,NY,PAS,2013-01-06T00:00:00.000,46,TAXI,TOYOT,P,32920,...,ALL,GRAY,0,2014,-,0,NaN,NaN,NaN,NaN
1996,1358688801,81817JX,NY,COM,2013-01-06T00:00:00.000,78,VAN,FORD,P,53420,...,ALL,WHITE,0,2004,-,0,NaN,NaN,NaN,NaN
1997,1361801244,GGS7747,NY,PAS,2013-01-06T00:00:00.000,40,SDN,MITSU,P,9030,...,ALL,BK,0,0,-,0,NaN,NaN,NaN,NaN
1998,1358688709,AD69352,AZ,PAS,2013-01-06T00:00:00.000,78,VAN,GMC,P,16620,...,ALL,WHITE,0,0,-,0,NaN,NaN,NaN,NaN
1999,1361442920,19758JT,NY,COM,2013-01-06T00:00:00.000,46,DELV,NaN,P,0,...,ALL,BROWN,0,0,-,0,NaN,NaN,NaN,NaN

In [7]:
def results(endpointdf, records):
        client = Socrata("data.cityofnewyork.us", None)
        data = client.get(endpointdf, limit=records)
        name = pd.DataFrame.from_records(data)
        return name 

results("jt7v-77mi", 10)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

,summons_number,plate_id,registration_state,plate_type,issue_date,violation_code,vehicle_body_type,vehicle_make,issuing_agency,street_code1,...,law_section,sub_division,days_parking_in_effect,from_hours_in_effect,to_hours_in_effect,vehicle_color,unregistered_vehicle,vehicle_year,meter_number,feet_from_curb
0,1361929741,FCJ5493,NY,PAS,1970-12-18T00:00:00.000,20,SUBN,GMC,S,35030,...,408,E2,BBBBBBB,ALL,ALL,BLACK,0,2013,-,0
1,1366962000,63540MC,NY,COM,1971-02-02T00:00:00.000,46,DELV,FRUEH,P,58830,...,408,F1,BBBBBBB,ALL,ALL,BRN,0,2013,-,0
2,1342296187,GCY4187,NY,SRF,1971-09-18T00:00:00.000,21,VAN,FORD,S,11790,...,408,D1,BBYBBBB,0930A,1100A,BLUE,0,2002,-,0
3,1342296199,95V6675,TX,PAS,1971-09-18T00:00:00.000,21,NaN,GMC,S,11790,...,408,D1,BBYBBBB,0930A,1100A,SILVR,0,2008,-,0
4,1342296217,FYM5117,NY,SRF,1971-09-18T00:00:00.000,21,SUBN,NISSA,S,28190,...,408,D1,BBYBBBB,0930A,1100A,WHITE,0,2012,-,0
5,1356906515,GFM1421,NY,PAS,1971-09-18T00:00:00.000,40,SDN,MAZDA,X,13610,...,408,C,BBBBBBB,ALL,ALL,BLK,0,2010,-,7
6,1337077380,18972BB,NY,999,1971-10-10T00:00:00.000,14,BUS,INTER,P,8440,...,408,C,BBBBBBB,0700A,0400P,YELLO,0,2001,-,0
7,1364523796,WNJ4730,VA,PAS,1973-04-05T00:00:00.000,14,SDN,TOYOT,P,50830,...,408,C,BBBBBBB,0400P,0700P,BLK,0,0,-,0
8,1359914924,68091JZ,NY,COM,1973-07-22T00:00:00.000,46,DELV,TOYOT,P,10610,...,408,F4,BBBBBBB,ALL,ALL,WH,0,2010,-,0
9,1355498326,EWV4127,NY,PAS,1973-08-12T00:00:00.000,21,SUBN,ACURA,X,42630,...,408,D1,YYYYYYB,0800A,0830A,GREY,0,2005,-,0